port: 49000

log:
  writefile: true
  filedir: logs
  filename: ai_arts_backend.log

db:
  username: root
  password: corona@2020@wuhan
  host: huawei-infra01.sigsus.cn
  port: 3306
  database: ai_arts
  maxopenconns: 10
  maxidleconns: 2

file:
  datasetdir: /test_data/dataset
  modeldir: /test_data/model
  sizelimit: 1000000000

Anno:
  backendUrl: https://huawei-proxy01.sigsus.cn

Infer:
  backendUrl: http://huawei-infra01.sigsus.cn

auth:
  url: "http://sandbox2-master.sigsus.cn:52080/custom-user-dashboard-backend/auth/currentUser"
  key: "Sign key for JWT"

DltsUrl: http://219.133.167.42:52009/apis
