port: 9000

log:
  writefile: true
  filedir: logs
  filename: ai_arts_backend.log

db:
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
  database: ai_arts
  maxopenconns: 10
  maxidleconns: 2
