port: 9000

log:
  writefile: true
  filedir: logs
  filename: ai_arts_backend.log

db:
  username: root
  password: apulis#2019#wednesday
  host: 192.168.3.2
  port: 3306
  database: ai_arts
  maxopenconns: 10
  maxidleconns: 2

file:
  datasetdir: /test_data/dataset
  modeldir: /test_data/model
  sizelimit: 1000000000

auth:
  url: "http://sandbox2-master.sigsus.cn:52080/custom-user-dashboard-backend/auth/currentUser"
  key: "Sign key for JWT"

dlts_platform_url: http://atlas02.sigsus.cn/apis
