definitions:
  models.Dataset:
    properties:
      createdAt:
        type: string
      creator:
        type: string
      deletedAt:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      path:
        type: string
      size:
        type: integer
      status:
        type: string
      updatedAt:
        type: string
      version:
        type: string
    type: object
  models.Modelset:
    properties:
      createdAt:
        type: string
      creator:
        type: string
      deletedAt:
        type: string
      description:
        type: string
      id:
        type: integer
      jobId:
        type: string
      name:
        type: string
      path:
        type: string
      size:
        type: integer
      status:
        type: string
      type:
        type: string
      updatedAt:
        type: string
      version:
        type: string
    type: object
  routers.APIException:
    properties:
      code:
        type: integer
      msg:
        type: string
    type: object
  routers.APISuccessResp:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  routers.APISuccessRespGetDataset:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/routers.GetDatasetResp'
      msg:
        type: string
    type: object
  routers.APISuccessRespGetDatasets:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/routers.GetDatasetsResp'
      msg:
        type: string
    type: object
  routers.APISuccessRespGetModelset:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/routers.GetModelsetResp'
      msg:
        type: string
    type: object
  routers.APISuccessRespGetModelsets:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/routers.GetModelsetsResp'
      msg:
        type: string
    type: object
  routers.APISuccessRespUploadFile:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/routers.UploadFileResp'
      msg:
        type: string
    type: object
  routers.GetDatasetResp:
    properties:
      dataset:
        $ref: '#/definitions/models.Dataset'
    type: object
  routers.GetDatasetsResp:
    properties:
      datasets:
        items:
          $ref: '#/definitions/models.Dataset'
        type: array
      pageNum:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
      totalPage:
        type: integer
    type: object
  routers.GetModelsetResp:
    properties:
      model:
        $ref: '#/definitions/models.Modelset'
    type: object
  routers.GetModelsetsResp:
    properties:
      models:
        items:
          $ref: '#/definitions/models.Modelset'
        type: array
      pageNum:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
      totalPage:
        type: integer
    type: object
  routers.UploadFileResp:
    properties:
      path:
        type: string
    type: object
  routers.createDatasetReq:
    properties:
      creator:
        type: string
      description:
        type: string
      name:
        type: string
      path:
        type: string
    required:
    - creator
    - description
    - name
    - path
    type: object
  routers.createModelsetReq:
    properties:
      creator:
        type: string
      description:
        type: string
      jobId:
        type: string
      name:
        type: string
      path:
        type: string
    required:
    - creator
    - description
    - jobId
    - name
    - path
    type: object
info:
  contact: {}
  license: {}
paths:
  /ai_arts/api/datasets:
    get:
      parameters:
      - description: page number, from 1
        in: query
        name: pageNum
        required: true
        type: integer
      - description: count per page
        in: query
        name: pageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/routers.APISuccessRespGetDatasets'
        "400":
          description: error
          schema:
            $ref: '#/definitions/routers.APIException'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/routers.APIException'
      summary: list datasets
    post:
      parameters:
      - description: json body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/routers.createDatasetReq'
      - description: dataset description
        in: body
        name: description
        required: true
        schema:
          type: string
      - description: dataset creator
        in: body
        name: creator
        required: true
        schema:
          type: string
      - description: dataset storage path
        in: body
        name: path
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/routers.APISuccessResp'
        "400":
          description: error
          schema:
            $ref: '#/definitions/routers.APIException'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/routers.APIException'
      summary: create dataset
  /ai_arts/api/datasets/:id:
    delete:
      parameters:
      - description: dataset id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/routers.APISuccessResp'
        "400":
          description: error
          schema:
            $ref: '#/definitions/routers.APIException'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/routers.APIException'
      summary: delete dataset by id
    get:
      parameters:
      - description: dataset id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/routers.APISuccessRespGetDataset'
        "400":
          description: error
          schema:
            $ref: '#/definitions/routers.APIException'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/routers.APIException'
      summary: get dataset by id
    post:
      parameters:
      - description: dataset description
        in: path
        name: description
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/routers.APISuccessResp'
        "400":
          description: error
          schema:
            $ref: '#/definitions/routers.APIException'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/routers.APIException'
      summary: update dataset
  /ai_arts/api/files/upload/dataset:
    post:
      parameters:
      - description: upload file key 'data'
        in: body
        name: data
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/routers.APISuccessRespUploadFile'
        "400":
          description: error
          schema:
            $ref: '#/definitions/routers.APIException'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/routers.APIException'
      summary: upload dataset file
  /ai_arts/api/files/upload/model:
    post:
      parameters:
      - description: upload file key 'data'
        in: body
        name: data
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/routers.APISuccessResp'
        "400":
          description: error
          schema:
            $ref: '#/definitions/routers.APIException'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/routers.APIException'
      summary: upload model file, not implemented yet
  /ai_arts/api/models:
    get:
      parameters:
      - description: page number, from 1
        in: query
        name: pageNum
        required: true
        type: integer
      - description: count per page
        in: query
        name: pageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/routers.APISuccessRespGetModelsets'
        "400":
          description: error
          schema:
            $ref: '#/definitions/routers.APIException'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/routers.APIException'
      summary: list models
    post:
      parameters:
      - description: json body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/routers.createModelsetReq'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/routers.APISuccessResp'
        "400":
          description: error
          schema:
            $ref: '#/definitions/routers.APIException'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/routers.APIException'
      summary: create model
  /ai_arts/api/models/:id:
    delete:
      parameters:
      - description: model id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/routers.APISuccessResp'
        "400":
          description: error
          schema:
            $ref: '#/definitions/routers.APIException'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/routers.APIException'
      summary: delete model by id
    get:
      parameters:
      - description: model id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/routers.APISuccessResp'
        "400":
          description: error
          schema:
            $ref: '#/definitions/routers.APIException'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/routers.APIException'
      summary: download model by id
    post:
      parameters:
      - description: model description
        in: path
        name: description
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/routers.APISuccessResp'
        "400":
          description: error
          schema:
            $ref: '#/definitions/routers.APIException'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/routers.APIException'
      summary: update model
  /api/annotations:
    post:
      parameters:
      - description: Name
        in: query
        name: name
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: query
        name: created_by
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: sample
  /api/codes:
    post:
      parameters:
      - description: Name
        in: query
        name: name
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: query
        name: created_by
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: sample
  /api/inferences:
    post:
      parameters:
      - description: Name
        in: query
        name: name
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: query
        name: created_by
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: sample
  /api/trainings:
    post:
      parameters:
      - description: Name
        in: query
        name: name
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: query
        name: created_by
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: sample
swagger: "2.0"
