definitions:
  models.Dataset:
    properties:
      created_at:
        type: string
      creator:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      path:
        type: string
      size:
        type: integer
      status:
        type: string
      updated_at:
        type: string
      version:
        type: string
    type: object
  routers.APIException:
    properties:
      code:
        type: integer
      msg:
        type: string
    type: object
  routers.APISuccessResp:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  routers.APISuccessRespGetDataset:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/routers.GetDatasetResp'
      msg:
        type: string
    type: object
  routers.APISuccessRespGetDatasets:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/routers.GetDatasetsResp'
      msg:
        type: string
    type: object
  routers.GetDatasetResp:
    properties:
      dataset:
        $ref: '#/definitions/models.Dataset'
    type: object
  routers.GetDatasetsResp:
    properties:
      count:
        type: integer
      datasets:
        items:
          $ref: '#/definitions/models.Dataset'
        type: array
      page:
        type: integer
      total:
        type: integer
    type: object
info:
  contact: {}
  license: {}
paths:
  /ai_arts/api/datasets:
    get:
      parameters:
      - description: page number
        in: query
        name: page
        required: true
        type: integer
      - description: count per page
        in: query
        name: count
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/routers.APISuccessRespGetDatasets'
        "400":
          description: error
          schema:
            $ref: '#/definitions/routers.APIException'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/routers.APIException'
      summary: list datasets
    post:
      parameters:
      - description: dataset name
        in: query
        name: name
        required: true
        type: string
      - description: dataset description
        in: query
        name: description
        required: true
        type: string
      - description: dataset creator
        in: query
        name: creator
        required: true
        type: string
      - description: dataset storage path
        in: query
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/routers.APISuccessResp'
        "400":
          description: error
          schema:
            $ref: '#/definitions/routers.APIException'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/routers.APIException'
      summary: create dataset
  /ai_arts/api/datasets/:id:
    delete:
      parameters:
      - description: dataset id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/routers.APISuccessResp'
        "400":
          description: error
          schema:
            $ref: '#/definitions/routers.APIException'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/routers.APIException'
      summary: delete dataset by id
    get:
      parameters:
      - description: dataset id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/routers.APISuccessRespGetDataset'
        "400":
          description: error
          schema:
            $ref: '#/definitions/routers.APIException'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/routers.APIException'
      summary: get dataset by id
    post:
      parameters:
      - description: dataset description
        in: query
        name: description
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/routers.APISuccessResp'
        "400":
          description: error
          schema:
            $ref: '#/definitions/routers.APIException'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/routers.APIException'
      summary: update dataset
  /ai_arts/api/files/upload/dataset:
    get:
      parameters:
      - description: upload file key 'data'
        in: query
        name: data
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/routers.APISuccessResp'
        "400":
          description: error
          schema:
            $ref: '#/definitions/routers.APIException'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/routers.APIException'
      summary: upload dataset file
  /ai_arts/api/files/upload/model:
    get:
      parameters:
      - description: upload file key 'data'
        in: query
        name: data
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/routers.APISuccessResp'
        "400":
          description: error
          schema:
            $ref: '#/definitions/routers.APIException'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/routers.APIException'
      summary: upload dataset file
  /api/annotations:
    post:
      parameters:
      - description: Name
        in: query
        name: name
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: query
        name: created_by
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: sample
  /api/codes:
    post:
      parameters:
      - description: Name
        in: query
        name: name
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: query
        name: created_by
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: sample
  /api/inferences:
    post:
      parameters:
      - description: Name
        in: query
        name: name
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: query
        name: created_by
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: sample
  /api/models:
    post:
      parameters:
      - description: Name
        in: query
        name: name
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: query
        name: created_by
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: sample
  /api/trainings:
    post:
      parameters:
      - description: Name
        in: query
        name: name
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: query
        name: created_by
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: sample
swagger: "2.0"
